### PR TITLE
Fix TypeError in RichJupyterWidget class

### LINKED ISSUE #211: Python 3.6: TypeError in RichJupyterWidget class
Trying to instantiate an object of type RichJupyterWidget with Python 3.6 causes a type error.

```
    _supported_format = [bytes(f) for f in QtGui.QImageReader.supportedImageFormats()]
TypeError: 'bytes' object cannot be interpreted as an integer

```

This program will reproduce the issue:

```
#!/usr/bin/python
import sys
from PySide.QtCore import *
from PySide.QtGui import *
from qtconsole.rich_jupyter_widget import RichJupyterWidget

app = QApplication(sys.argv)
widget = RichJupyterWidget()
widget.show()
app.exec_()
sys.exit()
```

### PR DESCRIPTION
**Pull request by TheHubbit**
Fixes #211.

This pull request fixes issue #211 for me. Tested with example on macOS Sierra 10.12.4 and Python 3.6.1.

### CODE REVIEW

**Comment by takluyver** [comment]
Unfortunately this is reverting part of #158, and it would break things again on PyQt5 + Python 3:

```
 4│ [str(f) for f in QtGui.QImageReader.supportedImageFormats()]
 4> 
["b'bmp'",
 "b'cur'",
 "b'dds'",
...

 5│ [bytes(f) for f in QtGui.QImageReader.supportedImageFormats()]
 5> 
[b'bmp',
 b'cur',
 b'dds',
...
```

**Comment by TheHubbit** [comment]
Thanks for pointing out the PyQt compatibility issue. I updated the pull request and tested with both PySide and PyQt5.

```python
#!/usr/bin/python
import sys
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from qtconsole.rich_jupyter_widget import RichJupyterWidget

app = QApplication(sys.argv)
widget = RichJupyterWidget()
print(widget._jpg_supported)
sys.exit()
```

**Comment by takluyver** [comment]
Thanks :-)

```
 9│ b
 9> PyQt5.QtCore.QByteArray(b'bmp')

 10│ b == 'bmp'
 10> True
```

It looks like PyQt treats bytes and strings as interchangeable. That's convenient in this case, but a bit disappointing in general.

**Comment by ccordoba12** [comment]
@takluyver, do you approve this one then?

**Comment by takluyver** [comment]
I haven't tested, but given what I tried above, it looks OK.

**Comment by Carreau** [comment]
That fixes things for me.

**Comment by ccordoba12** [comment]
Thanks @Carreau for the confirmation. Merging then.

**Comment by TheHubbit** [comment]
Thanks everyone for reviewing and merging!

**Pull request merged**
