### PR TITLE
Test usage of proactor event loop

### PR DESCRIPTION
**Pull request by blink1073**
Research for [discuss.python.org/t/removing-the-asyncio-policy-system-asyncio-set-event-loop-policy-in-python-3-15/37553/26](https://discuss.python.org/t/removing-the-asyncio-policy-system-asyncio-set-event-loop-policy-in-python-3-15/37553/26)

### CODE REVIEW

**Comment by blink1073** [comment]
@ccordoba12 do you have any concerns about this?

**Comment by blink1073** [comment]
For context, the ability to set an event loop policy might be going away.

**Comment by ccordoba12** [comment]
I thought this was necessary on Windows for Python 3.8+. How did it get fix?

**Comment by blink1073** [comment]
Hey @ccordoba12, tornado 6.1 added support for the proactor [loop](https://github.com/tornadoweb/tornado/blob/a6dfd70d7a6398b2187021df63ca77daa5781e5e/docs/releases/v6.1.0.rst#general-changes), by starting a thread. The `jupyter_server` test suite runs in about 10 min with the selector loop, and 15 min with the proactor loop.

Guido suggested that if we can switch from `ioloop.start()` to calling `asyncio.run(loop_factory=...)` ourselves, we could retain the proactor loop.

**Comment by ccordoba12** [comment]
@blink1073, thanks for the explanation. I must confess my ignorance about most asyncio related stuff because I haven't had time to learn about it.

So, if you consider this is no longer necessary then I'm ok with removing it.

**Comment by blink1073** [comment]
> So, if you consider this is no longer necessary then I'm ok with removing it.

I still need to do more testing to make sure we're future-proof (if they take away `set_event_loop_policy`, but thanks!

**Pull request closed without merging**
