### PR TITLE
add basic install/run to README

### PR DESCRIPTION
**Pull request by minrk**

### CODE REVIEW

**Comment by takluyver** [comment]
Installing with pip is only going to work if you have PyQt installed from another source, though. I'm not sure whether we should mention it, say what you've said, or skip over installation entirely.

**Comment by minrk** [comment]
Probably mentioning that PyQt/PySide must come from somewhere else is a good idea.

**Comment by damianavila** [comment]
>Probably mentioning that PyQt/PySide must come from somewhere else is a good idea.

Yep, I agree...

**Comment by minrk** [comment]
Added mention of PyQt/PySide

**Comment by damianavila** [comment]
:+1:

**Comment by takluyver** [comment]
I think that was the last thing to do before releasing this. @minrk , do you want to push the release button?

**Comment by minrk** [comment]
Yup, I'll hit it.

**Comment by minrk** [comment]
Released. I think that leaves only:

- jupyter/notebook
- ipython/ipywidgets
- ipython/ipython
- jupyter meta pkg

to finish for 4.0

**Comment by takluyver** [comment]
* New release of jupyter_core
* ipyparallel

**Comment by minrk** [comment]
@takluyver I did both of those today, too.

**Comment by takluyver** [comment]
Ninja releaser uses stealth!

**Pull request merged**
