### PR TITLE
Set application name for Linux desktop frameworks

### LINKED ISSUE #11: The value of WM_CLASS in IPython qtconsole is empty.
'WM_CLASS' variable is used in some desktop environments to associate apps with their corresponding '.desktop' file. IPython qtconsole's WM_CLASS seems to be empty.

    xprop WM_CLASS
    WM_CLASS(STRING) = "", ""

This makes the app to have no title in Gnome Shell.

Reference: https://wiki.gnome.org/Projects/GnomeShell/ApplicationBased

### PR DESCRIPTION
**Pull request by takluyver**
From the information I've seen, I think this is right, but I can't test it on GNOME 3 for a few more days.

Closes #12
Closes #11

### CODE REVIEW

**Comment by 183amir** [comment]
Your `WM_CLASS` variable doesn't have to be lower case letters while your `.desktop` file name should be all lowercase. Usually, the `WM_CLASS` variable has the same case as application's name.

This code would work too (and it is usually done this way):

    self.app = QtGui.QApplication(['Jupyter-qtconsole'])
    self.app.setApplicationName('Jupyter-qtconsole')

**Comment by takluyver** [comment]
But what's passed to `QApplication()` is usually the command line arguments, right? And commands are usually lower case.

**Comment by 183amir** [comment]
True. but how about `setApplicationName`?

**Comment by takluyver** [comment]
Should they be different? Does the capital letter really matter anyway? Can you test this branch (with the `jupyter-qtconsole.desktop` file installed)?

**Comment by takluyver** [comment]
This appears to be doing the right thing for me, so I'm merging it.

**Pull request merged**
