### PR TITLE
BUG: Rename width/height traits to avoid QWidget override.

### LINKED ISSUE #124: ConsoleWidget width/height traits override Qt properties
https://github.com/jupyter/qtconsole/blob/master/qtconsole/console_widget.py#L135-L143

These override the `width()` and `height()` Qt properties that are required to use this as a `QWidget` in many places. Can we rename them to `console_width/console_height`? I don't know how often these traits are actually used downstream. We override them right back to work around the problem.

### PR DESCRIPTION
**Pull request by rkern**
Fixes #124

Not sure what should be done with the changelog to document this.

### CODE REVIEW

**Comment by takluyver** [comment]
Put a note in the changelog. Technically, since the change breaks API and config, it should be for 5.0, but clashing with Qt properties seems broken enough that I think it could go into 4.3.

Ping @ccordoba12 .

**Comment by ccordoba12** [comment]
+1 from me :-)

**Comment by takluyver** [comment]
OK, feel free to merge and decide what release it goes in :-)

**Comment by rkern** [comment]
Thanks, all!

**Pull request merged**
