### PR TITLE
Set AppUserModelID for Windows 7 and later

### PR DESCRIPTION
**Pull request by ccordoba12**
This way qtconsole uses its assigned taskbar icon instead of grabbing the one with the same AppUserModelID (which usually is the Python one)

----

@minrk, could it be possible to have a minor 4.1.1 release this week with this little change? This way we could include it in Anaconda 2.4.1, to be released next week. Thanks :-)

### CODE REVIEW

**Comment by minrk** [comment]
Sure, no problem.

**Comment by ccordoba12** [comment]
Thanks a lot! Please ping me when it's ready to update the Anaconda 
packages :-)

**Comment by minrk** [comment]
Released 4.1.1 with this.

**Comment by ccordoba12** [comment]
Thanks a lot @minrk!

**Pull request merged**
