### PR TITLE
Refactorings by Sourcery.AI (Imporved memory usage)

### PR DESCRIPTION
**Pull request by Advik-B**
Improves code quality
uses the modern python syntax (walrus operators), etc
remove redundant `if conditions:` 
## improve lists (I don't know what else to call it): EXAMPLE
BEFORE
```py
items: list = []
for i in range(101):
    items.append(i)
```
AFTER
```py
items: list = [i for i in range(101)]
```

## Walrus operators:

BEFORE
```py
condition = something.get()
if condition:
    do.something()
```
AFTER
```py
if condition := something.get():
   do.something()
```
I believe the above ^^^ will decrease the mem usage. (correct me if I am wrong) 
## I really don't know that else to put here, check the commit messages by Sourcery for more info. 

---

## Anyway here is a table that  Sourcery made
# Sourcery Code Quality Report

✅ &nbsp;Merging this PR will **increase** code quality in the affected files by **0.06%**.

| Quality metrics | Before | After | Change |
| --- | :---: | :---: | :---: |
| [Complexity](https://docs.sourcery.ai/GitHub/Quality-Report/#complexity) | 15.55 🙂 | 15.46 🙂 | -0.09 👍 |
| [Method Length](https://docs.sourcery.ai/GitHub/Quality-Report/#method-length) | 57.25 ⭐ | 56.87 ⭐ | -0.38 👍 |
| [Working memory](https://docs.sourcery.ai/GitHub/Quality-Report/#working-memory) | 9.41 🙂 | 9.47 🙂 | 0.06 👎 |
| **[Quality](https://docs.sourcery.ai/GitHub/Quality-Report/#quality-score)** | **63.85%** 🙂| **63.91%** 🙂| **0.06%** 👍 |

| Other metrics | Before | After | Change |
| --- | :---: | :---: | :---: |
| Lines | 7885 | 7762 | -123 |

| Changed files | Quality Before | Quality After | Quality Change |
| --- | :---: | :---: | :---: |
| setup.py | 34.43% 😞 | 37.63% 😞 | 3.20% 👍|
| docs/gh-pages.py | 71.03% 🙂 | 73.67% 🙂 | 2.64% 👍|
| qtconsole/ansi_code_processor.py | 51.01% 🙂 | 51.67% 🙂 | 0.66% 👍|
| qtconsole/base_frontend_mixin.py | 80.25% ⭐ | 80.53% ⭐ | 0.28% 👍|
| qtconsole/call_tip_widget.py | 61.72% 🙂 | 62.70% 🙂 | 0.98% 👍|
| qtconsole/completion_html.py | 66.19% 🙂 | 66.62% 🙂 | 0.43% 👍|
| qtconsole/completion_widget.py | 66.57% 🙂 | 66.72% 🙂 | 0.15% 👍|
| qtconsole/console_widget.py | 54.98% 🙂 | 55.05% 🙂 | 0.07% 👍|
| qtconsole/frontend_widget.py | 71.80% 🙂 | 71.81% 🙂 | 0.01% 👍|
| qtconsole/history_console_widget.py | 67.25% 🙂 | 67.51% 🙂 | 0.26% 👍|
| qtconsole/inprocess.py | 94.12% ⭐ | 94.34% ⭐ | 0.22% 👍|
| qtconsole/jupyter_widget.py | 72.76% 🙂 | 72.77% 🙂 | 0.01% 👍|
| qtconsole/kill_ring.py | 93.63% ⭐ | 92.93% ⭐ | -0.70% 👎|
| qtconsole/mainwindow.py | 61.44% 🙂 | 61.50% 🙂 | 0.06% 👍|
| qtconsole/manager.py | 91.16% ⭐ | 91.29% ⭐ | 0.13% 👍|
| qtconsole/pygments_highlighter.py | 61.39% 🙂 | 61.47% 🙂 | 0.08% 👍|
| qtconsole/qtconsoleapp.py | 71.35% 🙂 | 71.36% 🙂 | 0.01% 👍|
| qtconsole/rich_jupyter_widget.py | 65.47% 🙂 | 65.20% 🙂 | -0.27% 👎|
| qtconsole/styles.py | 82.94% ⭐ | 81.90% ⭐ | -1.04% 👎|
| qtconsole/util.py | 79.17% ⭐ | 79.54% ⭐ | 0.37% 👍|
| qtconsole/tests/test_00_console_widget.py | 65.39% 🙂 | 65.39% 🙂 | 0.00% |

Here are some functions in these files that still need a tune-up:

| File | Function | Complexity | Length | Working Memory | Quality | Recommendation |
| --- | --- | :---: | :---: | :---: | :---: | --- |
| qtconsole/console_widget.py | ConsoleWidget.\_event\_filter\_console\_keypress | 166 ⛔ | 1416 ⛔ | 29 ⛔ | 1.03% ⛔ | Refactor to reduce nesting. Try splitting into smaller methods. Extract out complex expressions |
| qtconsole/console_widget.py | ConsoleWidget.\_insert\_plain\_text | 78 ⛔ | 396 ⛔ | 18 ⛔ | 7.53% ⛔ | Refactor to reduce nesting. Try splitting into smaller methods. Extract out complex expressions |
| qtconsole/mainwindow.py | MainWindow.close\_tab | 55 ⛔ | 403 ⛔ | 20 ⛔ | 7.78% ⛔ | Refactor to reduce nesting. Try splitting into smaller methods. Extract out complex expressions |
| qtconsole/pygments_highlighter.py | get\_tokens\_unprocessed | 52 ⛔ | 199 😞 | 16 ⛔ | 18.97% ⛔ | Refactor to reduce nesting. Try splitting into smaller methods. Extract out complex expressions |
| qtconsole/ansi_code_processor.py | AnsiCodeProcessor.set\_sgr\_code | 30 😞 | 224 ⛔ | 21 ⛔ | 20.02% ⛔ | Refactor to reduce nesting. Try splitting into smaller methods. Extract out complex expressions |

## Legend and Explanation

The emojis denote the absolute quality of the code:

 - ⭐ excellent
 - 🙂 good
 - 😞 poor
 - ⛔ very poor

The 👍 and 👎 indicate whether the quality has improved or gotten worse with this pull request.

***

Please see our documentation [here](https://docs.sourcery.ai/GitHub/Quality-Report/) for details on how these metrics are calculated.

We are actively working on this report - lots more documentation and extra metrics to come!

Help us [improve](https://research.typeform.com/to/j06Spdfr?type=quality_report&github_login=sourcery-ai%5Bbot%5D&base_repo=https%3A%2F%2Fgithub.com%2FAdvik-B%2Fqtconsole.git&base_remote_ref=refs%2Fpull%2F1%2Fhead&base_ref=sourcery%2Fmaster&base_sha=bbd1fc8336872060ad59fc2ce39ba0013cb64c5a&head_repo=https%3A%2F%2Fgithub.com%2FAdvik-B%2Fqtconsole.git&head_ref=sourcery%2Fsourcery%2Fmaster&base_pr_number=1&base_pr_state=open) this quality report!

### CODE REVIEW

**Comment by Advik-B** [comment]
Check the commits that say:
```
'Refactored by Sourcery'
```

**Comment by Advik-B** [comment]
See Advik-B#1 for more info

**Comment by ccordoba12** [comment]
Hey @Advik-B, thanks for your help. We can't depend on the walrus operator because this project needs to be compatible with Python 3.7.

Besides, the gains seem negligible (0.06%) to justify merging an automatic refactoring.

**Comment by Advik-B** [comment]
Ok, so... I should remove the walrus operator and? ( I will explicitly tell sorcery NOT to use it   )

**Comment by ccordoba12** [comment]
> afterwards I will close this PR

I don't understand. Do you want this PR merged? Or why are doing this?

**Comment by Advik-B** [comment]
Nevermind, I will close this, and submit another one **WITHOUT** the walrus operator, Thanks for your feedback

**Pull request closed without merging**
