### PR TITLE
Fixed background colors bleeding into borders

### PR DESCRIPTION
**Pull request by flying-sheep**
i also deduplicated and DRYed the style templates, and removed the hardcoded border color for dark themes.

in the future maybe we can draw the prompt color from the pygments theme?

### CODE REVIEW

**Comment by wmvanvliet** [comment]
which border are you talking about? I don't see any difference.

**Comment by flying-sheep** [comment]
I removed `QFrame { border: 1px solid grey; }` from the dark stylesheet.

**Comment by wmvanvliet** [comment]
Why was that border there in the first place?

**Comment by flying-sheep** [comment]
no idea, maybe someone thought it looked nice.

**Pull request merged**
