### PR TITLE
Update qtconsoleapp.py

### PR DESCRIPTION
**Pull request by 183amir**
Fixes jupyter/qtconsole#11
I did a quick test on my machine and it seems to work.

### CODE REVIEW

**Comment by Carreau** [comment]
Hum, with the renaming to Jupyter, I'm not sure `IPython` a the right choice :-)

**Comment by takluyver** [comment]
I think we need to work out what's going on a bit better:

- On my machine, I already see an application title in GNOME shell, without this change. Though it differs depending on if I start it from the command line or from a launcher. Which way are you starting it?
- The guide you posted said that the name needs to match the name of a `.desktop` file. That will probably be `ipython-qtconsole` or `ipython3-qtconsole`.
- @ccordoba12 reckons there's a similar issue on KDE; it would be good to know if that's the same or something else.

**Comment by ccordoba12** [comment]
This is the issue reported in our side about our lack of WM_CLASS: spyder-ide/spyder#2207.

According to the OP (a KDE developer), it was causing Spyder to be grouped with the wrong app in Plasma's taskbar. So there are other side effects besides the one reported on issue #11.

**Comment by takluyver** [comment]
OK, so it looks like we should be calling `self.app.setApplicationName()` as well. The [GNOME docs](https://wiki.gnome.org/Projects/GnomeShell/ApplicationBased) also say that the name should match the filename of the .desktop file, minus `.desktop`, which will be `jupyter-qtconsole` by the next release, I guess. I'm going to whistle up another PR with the changes I think are necessary.

**Comment by takluyver** [comment]
See #16

**Pull request closed without merging**
