### PR TITLE
Allow text to be added before the prompt while autocompleting

### PR DESCRIPTION
**Pull request by impact27**
Autocomplete will fail it text is added to the console between the autocomplete request and the autocomplet reply, even if this text is added before the prompt. I would expect this to fail only if the prompt is changed. Therefore, instead of checking the absolute position, this checks the prompt buffer and the position in the prompt buffer.

### CODE REVIEW

**Comment by ccordoba12** [comment]
> Autocomplete will fail it text is added to the console between the autocomplete request and the autocomplet reply, even if this text is added before the promp

When does this case appear?

**Comment by impact27** [comment]
This appears sometimes while debugging. Sometimes the kernel will send the prompt before sending the cout content. This is why the option of adding text before the prompt exist. If the user manages to ask for completion before the cout text is displayed, and the reply comes after, then this is triggered.

**Comment by impact27** [comment]
Of course, this is almost impossible for a user to do that, but CI can trigger this.

**Comment by ccordoba12** [comment]
Ok, I see. Thanks for the clarification.

**Pull request merged**
