### PR TITLE
Fix missing argument error when switching syntax highlighting styles on PySide2 & PySide6

### LINKED ISSUE #537: Changing syntax highlighting style doesn't work with PySide2 & PySide6
If I try to change the syntax highlighting style when PySide2 or PySide6 is installed, I get the following error. However, changing the style seems to work with PyQt5 and PyQt6.

image

### PR DESCRIPTION
**Pull request by firai**
Replace `lambda` in syntax highlighting style `QAction` with partial objects in `init_view_menu()` for compatibility with PySide2 and Pyside6 (without breaking compatibility with PyQt5 and PyQt6).

Fixes #537.

### CODE REVIEW

**Comment by firai** [comment]
P.S. Not sure if this is something that could be shimmed in qtpy as well, in case other projects run into the same thing.

**Comment by ccordoba12** [comment]
@firai, for next time, we don't require to maintain PRs branches always updated with master. So there's no need to keep merging them after merging other PRs.

PR #536 was a special case because tests were failing. That's basically our main requirement for a PR to be merged.

**Review by ccordoba12 — COMMENTED** [review]
Thanks for your help @firai!

**Review by ccordoba12 — APPROVED** [review]

**Comment by firai** [comment]
I only remerged because one of the tests randomly failed after I changed the order of imports, which didn't make any sense. I merged master more as a measure to retrigger the tests.

**Comment by ccordoba12** [comment]
I see, then you can leave the task of re-running our tests to us. They are a bit flaky, so failures happen sometimes.

**Pull request merged**
