### PR TITLE
Replace _get_block_plain_text() with QTextBlock.text() to fix segfault on Qt 6

### LINKED ISSUE #531: Segmentation fault attempting tab completion on Qt6
To reproduce: 

```
$ python3 -m venv .venv
$ source .venv/bin/activate
$ pip install pyqt6 qtconsole
$ ./.venv/bin/jupyter-qtconsole
```

Then type something like `import i<tab>` 

Curiously, some things work fine: `mi<tab>` correctly expands to `min`, but typing an open parenthesis and pressing tab again causes a crash. 

`(.venv) ~ Ⲗ [IPKernelApp] WARNING | Parent appears to have exited, shutting down.`

I'm attaching both the crash report (could be PyQt, since the crash report says it segfaulted in `QTextDocumentLayout::blockBoundingRect`, which I take to mean a crash in Qt code) and the requirements.txt for the virtual environment I made to test. 

Let me know if you need more information from me. 

[crash_report.txt](https://github.com/jupyter/qtconsole/files/8393723/crash_report.txt)
[test_env.txt](https://github.com/jupyter/qtconsole/files/8393724/test_env.txt)

### PR DESCRIPTION
**Pull request by firai**
Replace `_get_block_plain_text()` with `QTextBlock.text()`.

Fixes #531.

### CODE REVIEW

**Comment by ccordoba12** [comment]
Tests seems to be failing for reasons unrelated to this. I'll fix them in another PR.

**Comment by firai** [comment]
> Tests seems to be failing for reasons unrelated to this. I'll fix them in another PR.

PR #540 is proposed to fix the tests

**Comment by ccordoba12** [comment]
@firai, please rebase or merge this PR with the latest master to see if our tests pass now.

**Review by ccordoba12 — APPROVED** [review]
Thanks @firai for your help with this!

**Pull request merged**
