### PR TITLE
Set height for completion widget

### PR DESCRIPTION
**Pull request by Roffild**
```python
    gui_completion_height = Integer(0, config=True,
        help="""
        Set Height for completion.

        'droplist'
            Height in pixels.
        'ncurses'
            Maximum number of rows.
        """
    )
```

In my confing now:
```python
c.ConsoleWidget.gui_completion = 'droplist'
c.ConsoleWidget.gui_completion_height = 600
```

### CODE REVIEW

**Comment by Roffild** [comment]
gui_completion_height600

**Comment by ccordoba12** [comment]
Hey @Roffild, thanks for the ping, I just missed your work when you submitted it.

To proceed, please merge your branch with the latest master so you can solve the merge conflicts. If you need help with that, let us know.

**Comment by Roffild** [comment]
Finish

**Review by ccordoba12 — APPROVED** [review]
Looks good to me, thanks @Roffild!

**Pull request merged**
