### PR TITLE
Add QtPrintSupport to QtGui compatibility bucket

### PR DESCRIPTION
**Pull request by takluyver**
Closes gh-160

Tested manually with PyQt5. I haven't tried with PySide2, I just copied the code.

### CODE REVIEW

**Comment by ccordoba12** [comment]
LGTM, thanks Thomas!

**Comment by ccordoba12** [comment]
@minrk or @takluyver, I think 4.3 is ready to be released!

**Comment by takluyver** [comment]
I think so too :-). I'm just off for lunch, but I've added you to the package on PyPI, so you should be able to make a release yourself. Don't forget to update the changelog in the docs!

**Comment by minrk** [comment]
@ccordoba12 did you want to try your hand at making a release (and updating the changelog)? If not, I can push it through.

**Comment by ccordoba12** [comment]
Sure, I just need some guidance to start with :-)

How do I update the changelog? And do you have a documented release procedure?

**Comment by minrk** [comment]
@ccordoba12 [here](http://jupyter.readthedocs.io/en/latest/developer-docs/releasing.html) is a general outline for releasing a Jupyter repo. Feel free to ask any further questions. The changelog is in docs/source/changelog.rst.

**Pull request merged**
