### PR TITLE
jupyer typo

### LINKED ISSUE #74: Docs Typo
There's a typo at:

http://jupyter.org/qtconsole/stable/config_options.html

>>
These options can be set in ~/.jupyer/jupyter_qtconsole_config.py, or at the command line when you start it.
<

Note the missing 't' in `.jupyter`.  I was looking for the docs to fix and submit a pull request, but it looks like the source rst file `docs/source/config_options.rst` is excluded from the repo via `.gitignore`...?

### PR DESCRIPTION
**Pull request by minrk**
closes #74

### CODE REVIEW

**Comment by bartekbrak** [comment]
I can still see this typo on https://jupyter.org/qtconsole/stable/config_options.html.

**Comment by takluyver** [comment]
Now that we can build Qt console docs on RTD, the latest are here:

http://qtconsole.readthedocs.io/en/latest/config_options.html

**Comment by bartekbrak** [comment]
Thanks, 

Is it possible to take `http://jupyter.org/qtconsole/` docs down? Can you? Who should I talk to? Obviously it is not desirable to have outdated doc anywhere online.

**Comment by minrk** [comment]
#167 should redirect those pages to RTD

**Pull request merged**
