### PR TITLE
Add license file

### LINKED ISSUE #233: Missing license file
License missing from repo

### PR DESCRIPTION
**Pull request by sumalaika**
Fixes #233.

Added license

### CODE REVIEW

**Comment by ccordoba12** [comment]
@willingc, is this change of for the Jupyter organization?

**Comment by willingc** [comment]
@ccordoba12 Looks good to me. Feel free to merge :-)

**Comment by ccordoba12** [comment]
Thanks @willingc!

**Comment by Carreau** [comment]
MANIFEST.in has not been updated to reflect the filename change.

**Pull request merged**
