### PR TITLE
remove remaining references to IPython

### PR DESCRIPTION
**Pull request by minrk**
- IPythonWidget is now JupyterWidget, etc.
- IPythonWidget config continues to work, with warnings
- IPythonWidget remains, with warnings

### CODE REVIEW

**Comment by minrk** [comment]
based on #24

**Comment by minrk** [comment]
Sorry, didn't notice this had conflicts. Should be ready to go, assuming Travis agrees.

**Comment by takluyver** [comment]
Should we add subtstitutions to the config migration stuff in jupyter_core to change `[Rich]IPythonWidget` to `[Rich]JupyterWidget`? And then probably push out a quick release of that so it's in place before people start running the migration.

**Comment by minrk** [comment]
Yes, I'll do that.

**Comment by minrk** [comment]
jupyter/jupyter_core#36

**Pull request merged**
