### PR TITLE
KernelManager.post_start_kernel is async in jupyter_client>=7.0

### PR DESCRIPTION
**Pull request by davidbrochart**
Fixes https://github.com/jupyter/qtconsole/pull/493/checks?check_run_id=3203252222

### CODE REVIEW

**Comment by ccordoba12** [comment]
Looks good to me, but I'll let @impact27 to take a look at this one because he was the one who added support for `post_start_kernel`.

**Comment by impact27** [comment]
Looks good to me

**Review by ccordoba12 — APPROVED** [review]
Thanks @davidbrochart!

**Comment by davidbrochart** [comment]
@ccordoba12 @impact27 I'm afraid we need to roll back this PR, see https://github.com/jupyter/jupyter_client/pull/670#issuecomment-892683920.

**Comment by ccordoba12** [comment]
Ok, no prob. Please open a new PR to perform the rollback.

**Pull request merged**
