### PR TITLE
Eliminate training whitespace

### PR DESCRIPTION
**Pull request by wmvanvliet**
Get rid of all training whitespace. This gets placed by accident. Let's clean it up!

Ran the following on the source code:

    python -m autopep8 --select W2 -i qtconsole/*.py
    python -m autopep8 --select W2 -i qtconsole/tests/*.py

### CODE REVIEW

**Comment by ccordoba12** [comment]
@takluyver, what do you think about this one?

**Comment by takluyver** [comment]
I generally think it's not worth it, but this is a fairly small diff, and it avoids having to ask people to redo changes where they've accidentally stripped out the whitespace. You and @wmvanvliet are doing most of the maintenance on qtconsole now, so it's up to you!

**Comment by wmvanvliet** [comment]
It's a small thing yes, but it took me only 5 seconds to run the command to auto-trim whitespace everywhere, it was either that or taking another sip of coffee :)

**Comment by takluyver** [comment]
I mean that because it's small, it's unlikely to cause much pain by conflicting with other changes. :-)

Let's do it.

**Comment by CAM-Gerlach** [comment]
Just FYI—its "trailing" whitespace, not "training".

**Pull request merged**
